version: "3.4"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=interviewer
      - MYSQL_USER=api-platform
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:4.7.6
    ports:
      - "8090:8080"

volumes:
  db_data:
